#include <gtest/gtest.h>
#include <vector>
#include "../protocol_nmea.h"
#include "../ISEarth.h"
using namespace std;


#define ASCII_BUF_LEN   200
#define POS_LAT_DEG     40.330578
#define POS_LON_DEG     -111.725816
#define POS_ALT_M       1406.39
#define LEAP_SEC        18

TEST(protocol_nmea, INFO)
{
    dev_info_t info = {};
    info.serialNumber = 1234;
    for (int i=0; i<4; i++)
    {
        info.hardwareVer[i] = 10+i;
        info.firmwareVer[i] = 20+i;
    }
    info.buildNumber = 5678;
    for (int i=0; i<4; i++)
    {
        info.protocolVer[i] = 30+i;
    }
    info.repoRevision = 789;
    snprintf(info.manufacturer, DEVINFO_MANUFACTURER_STRLEN, "manufacturer string 123");
    for (int i=0; i<4; i++)
    {
        info.buildDate[i] = i;
        info.buildTime[i] = i+4;
    }
    info.buildDate[0] = 0;
    snprintf(info.addInfo, DEVINFO_ADDINFO_STRLEN, "additional string   123");

    char ascii_buf[ASCII_BUF_LEN] = { 0 };
    did_dev_info_to_nmea_info(ascii_buf, ASCII_BUF_LEN, info);
    // printf("%s\n", ascii_buf);
    dev_info_t result = {};
    nmea_info_to_did_dev_info(result, ascii_buf, ASCII_BUF_LEN);
    ASSERT_EQ(memcmp(&info, &result, sizeof(result)), 0);
}

TEST(protocol_nmea, PIMU)
{
    imu_t imu = {};
    imu.time = 123.456;
    for (int i=0; i<3; i++)
    {
        imu.I.pqr[i] = 10.0f+i;
        imu.I.acc[i] = 20.0f+i;
    }

    char ascii_buf[ASCII_BUF_LEN] = { 0 };
    did_imu_to_nmea_pimu(ascii_buf, ASCII_BUF_LEN, imu, "$PIMU");
    // printf("%s\n", ascii_buf);
    imu_t result = {};
    nmea_pimu_to_did_imu(result, ascii_buf, ASCII_BUF_LEN);
    ASSERT_EQ(memcmp(&imu, &result, sizeof(result)), 0);
}

TEST(protocol_nmea, PRIMU)
{
    imu_t imu = {};
    imu.time = 123.456;
    for (int i=0; i<3; i++)
    {
        imu.I.pqr[i] = 10.0f+i;
        imu.I.acc[i] = 20.0f+i;
    }

    char ascii_buf[ASCII_BUF_LEN] = { 0 };
    did_imu_to_nmea_pimu(ascii_buf, ASCII_BUF_LEN, imu, "$PRIMU");
    // printf("%s\n", ascii_buf);
    imu_t result = {};
    nmea_pimu_to_did_rimu(result, ascii_buf, ASCII_BUF_LEN);
    ASSERT_EQ(memcmp(&imu, &result, sizeof(result)), 0);
}

TEST(protocol_nmea, PPIMU)
{
    pimu_t pimu = {};
    pimu.time = 123.456;
    pimu.dt = 7.89f;
    for (int i=0; i<3; i++)
    {
        pimu.theta[i] = 10.0f+i;
        pimu.vel[i] = 20.0f+i;
    }

    char ascii_buf[ASCII_BUF_LEN] = { 0 };
    did_pimu_to_nmea_ppimu(ascii_buf, ASCII_BUF_LEN, pimu);
    // printf("%s\n", ascii_buf);
    pimu_t result = {};
    nmea_ppimu_to_did_pimu(result, ascii_buf, ASCII_BUF_LEN);
    ASSERT_EQ(memcmp(&pimu, &result, sizeof(result)), 0);
}

TEST(protocol_nmea, PINS1)
{
    ins_1_t ins = {};
    ins.week = 12;
    ins.timeOfWeek = 3.456;
    ins.insStatus = 789;
    ins.hdwStatus = 123;
    for (int i=0; i<3; i++)
    {
        ins.theta[i] = 10.0f+i;
        ins.uvw[i] = 20.0f+i;
        ins.ned[i] = 40.0f+i;
    }
    ins.lla[0] = POS_LAT_DEG;
    ins.lla[1] = POS_LON_DEG;
    ins.lla[2] = POS_ALT_M;

    char ascii_buf[ASCII_BUF_LEN] = { 0 };
    did_ins1_to_nmea_pins1(ascii_buf, ASCII_BUF_LEN, ins);
    // printf("%s\n", ascii_buf);
    ins_1_t result = {};
    nmea_pins1_to_did_ins1(result, ascii_buf, ASCII_BUF_LEN);
    ASSERT_EQ(memcmp(&ins, &result, sizeof(result)), 0);
}

TEST(protocol_nmea, PINS2)
{
    ins_2_t ins = {};
    ins.week = 12;
    ins.timeOfWeek = 3.456;
    ins.insStatus = 789;
    ins.hdwStatus = 123;
    for (int i=0; i<3; i++)
    {
        ins.qn2b[i] = 10.0f+i;
    }
    for (int i=0; i<3; i++)
    {
        ins.uvw[i] = 20.0f+i;
    }
    ins.lla[0] = POS_LAT_DEG;
    ins.lla[1] = POS_LON_DEG;
    ins.lla[2] = POS_ALT_M;

    char ascii_buf[ASCII_BUF_LEN] = { 0 };
    did_ins2_to_nmea_pins2(ascii_buf, ASCII_BUF_LEN, ins);
    // printf("%s\n", ascii_buf);
    ins_2_t result = {};
    nmea_pins2_to_did_ins2(result, ascii_buf, ASCII_BUF_LEN);
    ASSERT_EQ(memcmp(&ins, &result, sizeof(result)), 0);
}

TEST(protocol_nmea, PGPSP)
{
    gps_pos_t pos = {};
    gps_vel_t vel = {};
    pos.week = 1;
    pos.timeOfWeekMs = vel.timeOfWeekMs = 370659600;
    pos.satsUsed = 45;
    pos.status = GPS_STATUS_NUM_SATS_USED_MASK & pos.satsUsed;
    for (int i=0; i<3; i++)
    {
        // pos.ecef[i] = 20.0f+i;   // Not in full conversion
        vel.vel[i] = 40.0f+i;
    }
    pos.lla[0] = POS_LAT_DEG;
    pos.lla[1] = POS_LON_DEG;
    pos.lla[2] = POS_ALT_M;
    pos.hMSL = 89;
    pos.hAcc = 123;
    pos.vAcc = 45;
    pos.pDop = 6;
    pos.cnoMean = 78;
    pos.towOffset = 9;
    pos.leapS = 12;
    vel.sAcc = 345;

    char ascii_buf[ASCII_BUF_LEN] = { 0 };
    did_gps_to_nmea_pgpsp(ascii_buf, ASCII_BUF_LEN, pos, vel);
    // printf("%s\n", ascii_buf);
    gps_pos_t resultPos = {};
    gps_vel_t resultVel = {};
    nmea_pgpsp_to_did_gps(resultPos, resultVel, ascii_buf, ASCII_BUF_LEN);
    ASSERT_EQ(memcmp(&pos, &resultPos, sizeof(resultPos)), 0);
    ASSERT_EQ(memcmp(&vel, &resultVel, sizeof(resultVel)), 0);
}

TEST(protocol_nmea, GGA)
{
    char gga[ASCII_BUF_LEN] = {0};
    snprintf(gga, ASCII_BUF_LEN, "$GNGGA,231100.200,4003.34247,N,11139.51850,W,2,12,0.47,1438.20,M,-18.80,M,,*73\r\n");
    gps_pos_t pos = {};
    pos.week = 2260;
    pos.timeOfWeekMs = 342678200;
    pos.satsUsed = 12;
    pos.status = 
        GPS_STATUS_NUM_SATS_USED_MASK & pos.satsUsed |
        GPS_STATUS_FLAGS_FIX_OK |
        GPS_STATUS_FLAGS_DGPS_USED |
        GPS_STATUS_FIX_DGPS |
        GPS_STATUS_FLAGS_GPS_NMEA_DATA;        
    pos.hMSL = 1438.2;
    pos.lla[0] =  ( 40.0 +  3.34247/60.0);
    pos.lla[1] = -(111.0 + 39.51850/60.0);
    pos.lla[2] = pos.hMSL - 18.8;
    pos.pDop = 0.47;
    pos.leapS = LEAP_SEC;
	// Convert LLA to ECEF.  Ensure LLA uses ellipsoid altitude
	ixVector3d lla;
	lla[0] = DEG2RAD(pos.lla[0]);
	lla[1] = DEG2RAD(pos.lla[1]);
	lla[2] = pos.lla[2];		// Use ellipsoid altitude
	lla2ecef(lla, pos.ecef);

    char ascii_buf[ASCII_BUF_LEN] = { 0 };
    int n = did_gps_to_nmea_gga(ascii_buf, ASCII_BUF_LEN, pos);
    // printf("%s\n", gga);
    // printf("%s\n", ascii_buf);
    ASSERT_EQ(memcmp(&gga, &ascii_buf, n), 0);

    gps_pos_t result = {};
    result.week = pos.week;
    result.leapS = pos.leapS;
    uint32_t weekday = pos.timeOfWeekMs / 86400000;
    nmea_gga_to_did_gps(result, ascii_buf, ASCII_BUF_LEN, weekday);
    pos.hAcc = result.hAcc;
    ASSERT_EQ(memcmp(&pos, &result, sizeof(result)), 0);
}

TEST(protocol_nmea, GGL)
{
    gps_pos_t pos = {};
    // pos.week = 12;
    pos.timeOfWeekMs = 370659600;
    pos.status = GPS_STATUS_NUM_SATS_USED_MASK & pos.satsUsed;
    pos.lla[0] = POS_LAT_DEG;
    pos.lla[1] = POS_LON_DEG;
    pos.leapS = LEAP_SEC;

    char ascii_buf[ASCII_BUF_LEN] = { 0 };
    did_gps_to_nmea_gll(ascii_buf, ASCII_BUF_LEN, pos);
    // printf("%s\n", ascii_buf);
    gps_pos_t result = {};
    result.leapS = pos.leapS;
    uint32_t weekday = pos.timeOfWeekMs / 86400000;
    nmea_gll_to_did_gps(result, ascii_buf, ASCII_BUF_LEN, weekday);
    ASSERT_EQ(memcmp(&pos, &result, sizeof(result)), 0);
}

TEST(protocol_nmea, GSA)
{
    gps_pos_t pos = {};
    pos.pDop = 6;
    pos.hAcc = 7;
    pos.vAcc = 8;

    gps_sat_t sat = {};
	for (uint32_t i = 0; i < 10; i++)
    {
        sat.sat[i].svId = i+1;
    }

    char ascii_buf[ASCII_BUF_LEN] = { 0 };
    did_gps_to_nmea_gsa(ascii_buf, ASCII_BUF_LEN, pos, sat);
    // printf("%s\n", ascii_buf);
    gps_pos_t resultPos = {};
    gps_sat_t resultSat = {};
    nmea_gsa_to_did_gps(resultPos, resultSat, ascii_buf, ASCII_BUF_LEN);
    ASSERT_EQ(memcmp(&pos, &resultPos, sizeof(resultPos)), 0);
    ASSERT_EQ(memcmp(&sat, &resultSat, sizeof(resultSat)), 0);
}

#define ASCII_BUF2  2048
char g_ascii_buf[ASCII_BUF2] = { 0 };

#if 1
TEST(protocol_nmea_4p11, GSV)
{
    string buf;

    // GPS & SBAS        #msgs,msg#,numSV,  svid,elv,azm,cno, ..., signalId*checksum
    buf += "$GPGSV,4,1,14," "02,40,310,43," "08,07,324,31," "10,48,267,45," "15,37,053,45," "1*67\r\n";
    buf += "$GPGSV,4,2,14," "16,12,268,35," "18,69,078,41," "23,74,336,40," "24,15,111,37," "1*62\r\n";
    buf += "$GPGSV,4,3,14," "26,02,239,31," "27,35,307,38," "29,12,162,37," "32,14,199,39," "1*60\r\n";
    buf += "$GPGSV,4,4,14," "44,43,188,43," "46,40,206,43,"                                 "1*65\r\n";
    buf += "$GPGSV,3,1,09," "10,48,267,45," "15,37,053,26," "18,69,078,34," "23,74,336,34," "6*6C\r\n";
    buf += "$GPGSV,3,2,09," "24,15,111,25," "26,02,239,18," "27,35,307,27," "29,12,162,21," "6*64\r\n";
    buf += "$GPGSV,3,3,09," "32,14,199,25,"                                                 "6*58\r\n";
    // Galileo
    buf += "$GAGSV,1,1,04," "05,65,144,30," "09,39,052,30," "34,71,341,27," "36,46,105,30," "2*73\r\n";
    buf += "$GAGSV,1,1,04," "05,65,144,41," "09,39,052,43," "34,71,341,42," "36,46,105,39," "7*7E\r\n";
    // Beidou
    buf += "$GBGSV,2,1,08," "11,09,141,34," "14,52,047,44," "27,32,313,43," "28,80,263,44," "1*71\r\n";
    buf += "$GBGSV,2,2,08," "33,81,039,43," "41,43,230,42," "43,33,148,42," "58,,,44,"      "1*4E\r\n";
    buf += "$GBGSV,1,1,02," "11,09,141,16," "14,52,047,32,"                                 "B*0D\r\n";
    // QZSS
    buf += "$GQGSV,1,1,01," "02,,,30,"                                                      "1*65\r\n";
    // GLONASS
    buf += "$GLGSV,2,1,06," "65,85,260,33," "66,28,217,30," "72,36,034,35," "81,20,324,33," "1*75\r\n";
    buf += "$GLGSV,2,2,06," "87,47,127,35," "88,73,350,34,"                                 "1*75\r\n";
    buf += "$GLGSV,1,1,01," "87,47,127,20,"                                                 "3*41\r\n";
    buf += "$GLGSV,1,1,01," "80,01,343,,"                                                   "0*45\r\n";

    gps_sat_t gpsSat = {};
    gpsSat.numSats = 31;
    gpsSat.timeOfWeekMs = 436693200;
    gps_sat_sv_t *sat = &(gpsSat.sat[0]);
    sat->azim = 310;
    sat->cno = 43;
    sat->elev = 40;
    sat->gnssId = 1;
    sat->status = 95;
    sat->svId = 2;
    sat++;
    sat->azim = 324;
    sat->cno = 45;
    sat->elev = 07;
    sat->gnssId = 1;
    sat->status = 95;
    sat->svId = 8;
    sat++;
    sat->azim = 267;
    sat->cno = 45;
    sat->elev = 48;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 10;
    sat++;
    sat->azim = 53;
    sat->cno = 45;
    sat->elev = 37;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 15;
    sat++;
    sat->azim = 268;
    sat->cno = 35;
    sat->elev = 12;
    sat->gnssId = 1;
    sat->status = 95;
    sat->svId = 16;
    sat++;
    sat->azim = 78;
    sat->cno = 41;
    sat->elev = 69;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 18;
    sat++;
    sat->azim = 336;
    sat->cno = 40;
    sat->elev = 74;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 23;
    sat++;
    sat->azim = 111;
    sat->cno = 37;
    sat->elev = 15;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 24;
    sat++;
    sat->azim = 239;
    sat->cno = 31;
    sat->elev = 02;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 26;
    sat++;
    sat->azim = 307;
    sat->cno = 38;
    sat->elev = 35;
    sat->gnssId = 1;
    sat->status = 95;
    sat->svId = 27;
    sat++;
    sat->azim = 162;
    sat->cno = 37;
    sat->elev = 12;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 29;
    sat++;
    sat->azim = 199;
    sat->cno = 39;
    sat->elev = 14;
    sat->gnssId = 1;
    sat->status = 95;
    sat->svId = 32;
    sat++;
    sat->azim = 188;
    sat->cno = 43;
    sat->elev = 43;
    sat->gnssId = 2;
    sat->status = 95;
    sat->svId = 131;
    sat++;
    sat->azim = 206;
    sat->cno = 43;
    sat->elev = 40;
    sat->gnssId = 2;
    sat->status = 95;
    sat->svId = 133;
    sat++;
    sat->azim = 173;
    sat->cno = 0;
    sat->elev = 43;
    sat->gnssId = 2;
    sat->status = 1;
    sat->svId = 138;
    sat++;
    sat->azim = 145;
    sat->cno = 41;
    sat->elev = 65;
    sat->gnssId = 3;
    sat->status = 31;
    sat->svId = 5;
    sat++;
    sat->azim = 53;
    sat->cno = 43;
    sat->elev = 39;
    sat->gnssId = 3;
    sat->status = 31;
    sat->svId = 9;
    sat++;
    sat->azim = 340;
    sat->cno = 42;
    sat->elev = 71;
    sat->gnssId = 3;
    sat->status = 31;
    sat->svId = 34;
    sat++;
    sat->azim = 104;
    sat->cno = 40;
    sat->elev = 47;
    sat->gnssId = 3;
    sat->status = 31;
    sat->svId = 36;
    sat++;
    sat->azim = 141;
    sat->cno = 36;
    sat->elev = 9;
    sat->gnssId = 4;
    sat->status = 23;
    sat->svId = 11;
    sat++;
    sat->azim = 47;
    sat->cno = 44;
    sat->elev = 52;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 14;
    sat++;
    sat->azim = 313;
    sat->cno = 38;
    sat->elev = 31;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 27;
    sat++;
    sat->azim = 267;
    sat->cno = 44;
    sat->elev = 79;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 28;
    sat++;
    sat->azim = 40;
    sat->cno = 42;
    sat->elev = 82;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 33;
    sat++;
    sat->azim = 230;
    sat->cno = 43;
    sat->elev = 43;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 41;
    sat++;
    sat->azim = 148;
    sat->cno = 43;
    sat->elev = 34;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 43;
    sat++;
    sat->azim = 0;
    sat->cno = 43;
    sat->elev = 0;
    sat->gnssId = 4;
    sat->status = 39;
    sat->svId = 58;
    sat++;
    sat->azim = 252;
    sat->cno = 31;
    sat->elev = 85;
    sat->gnssId = 6;
    sat->status = 23;
    sat->svId = 1;
    sat++;
    sat->azim = 217;
    sat->cno = 29;
    sat->elev = 28;
    sat->gnssId = 6;
    sat->status = 31;
    sat->svId = 2;
    sat++;
    sat->azim = 34;
    sat->cno = 35;
    sat->elev = 37;
    sat->gnssId = 6;
    sat->status = 31;
    sat->svId = 8;
    sat++;
    sat->azim = 344;
    sat->cno = 0;
    sat->elev = 1;
    sat->gnssId = 6;
    sat->status = 17;
    sat->svId = 16;
    sat++;
    sat->azim = 324;
    sat->cno = 19;
    sat->elev = 19;
    sat->gnssId = 6;
    sat->status = 19;
    sat->svId = 17;
    sat++;
    sat->azim = 126;
    sat->cno = 36;
    sat->elev = 48;
    sat->gnssId = 6;
    sat->status = 31;
    sat->svId = 23;
    sat++;
    sat->azim = 349;
    sat->cno = 32;
    sat->elev = 72;
    sat->gnssId = 6;
    sat->status = 28;
    sat->svId = 24;
    sat++;
    sat->azim = 374;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 40;
    sat->status = 0;
    sat->svId = 243;
    sat++;
    sat->azim = 374;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 0;
    sat->status = 0;
    sat->svId = 239;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 0;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 1;
    sat->elev = 1;
    sat->gnssId = 4;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 2;
    sat->elev = 0;
    sat->gnssId = 0;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 3;
    sat->cno = 0;
    sat->elev = 4;
    sat->gnssId = 7;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 72;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 1;
    sat->elev = 0;
    sat->gnssId = 1;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 0;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 0;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 82;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 1;
    sat->elev = 18;
    sat->gnssId = 160;
    sat->status = 0;
    sat->svId = 234;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 4;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 1;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 82;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 127;
    sat->elev = 0;
    sat->gnssId = 42;
    sat->status = 0;
    sat->svId = 66;

    // Check array out of bounds
    ASSERT_TRUE( sat < &(gpsSat.sat[MAX_NUM_SATELLITES]) );



    gps_sig_t gpsSig = {};
    gpsSig.numSigs = 58;
    gpsSig.timeOfWeekMs = 436693200;
    gps_sig_sv_t *sig = &(gpsSig.sig[0]);
    sig->cno = 43;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 361;
    sig->svId = 2;   
    sig++;
    sig->cno = 0;
    sig->gnssId = 1;
    sig->quality = 1;
    sig->sigId = 4;
    sig->status = 1;
    sig->svId = 2;
    sig++;
    sig->cno = 31;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 8;
    sig++;
    sig->cno = 45;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 10;
    sig++;
    sig->cno = 45;
    sig->gnssId = 1;
    sig->quality = 4;
    sig->sigId = 3;
    sig->status = 41;
    sig->svId = 10;
    sig++;
    sig->cno = 45;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 15;
    sig++;
    sig->cno = 27;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 3;
    sig->status = 41;
    sig->svId = 15;
    sig++;
    sig->cno = 37;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 361;
    sig->svId = 16;
    sig++;
    sig->cno = 0;
    sig->gnssId = 1;
    sig->quality = 1;
    sig->sigId = 4;
    sig->status = 1;
    sig->svId = 16;
    sig++;
    sig->cno = 41;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 18;
    sig++;
    sig->cno = 33;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 3;
    sig->status = 41;
    sig->svId = 18;
    sig++;
    sig->cno = 41;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 23;
    sig++;
    sig->cno = 34;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 3;
    sig->status = 41;
    sig->svId = 23;
    sig++;
    sig->cno = 37;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 24;
    sig++;
    sig->cno = 31;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 26;
    sig++;
    sig->cno = 41;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 361;
    sig->svId = 27;
    sig++;
    sig->cno = 23;
    sig->gnssId = 1;
    sig->quality = 4;
    sig->sigId = 3;
    sig->status = 9;
    sig->svId = 27;
    sig++;
    sig->cno = 36;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 29;
    sig++;
    sig->cno = 25;
    sig->gnssId = 1;
    sig->quality = 4;
    sig->sigId = 3;
    sig->status = 41;
    sig->svId = 29;
    sig++;
    sig->cno = 40;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 361;
    sig->svId = 32;
    sig++;
    sig->cno = 28;
    sig->gnssId = 1;
    sig->quality = 7;
    sig->sigId = 3;
    sig->status = 41;
    sig->svId = 32;
    sig++;
    sig->cno = 43;
    sig->gnssId = 2;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 361;
    sig->svId = 131;
    sig++;
    sig->cno = 43;
    sig->gnssId = 2;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 361;
    sig->svId = 133;
    sig++;
    sig->cno = 0;
    sig->gnssId = 2;
    sig->quality = 1;
    sig->sigId = 0;
    sig->status = 0;
    sig->svId = 138;
    sig++;
    sig->cno = 41;
    sig->gnssId = 3;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 5;
    sig++;
    sig->cno = 30;
    sig->gnssId = 3;
    sig->quality = 7;
    sig->sigId = 6;
    sig->status = 41;
    sig->svId = 5;
    sig++;
    sig->cno = 43;
    sig->gnssId = 3;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 9;
    sig++;
    sig->cno = 30;
    sig->gnssId = 3;
    sig->quality = 7;
    sig->sigId = 6;
    sig->status = 41;
    sig->svId = 9;
    sig++;
    sig->cno = 42;
    sig->gnssId = 3;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 34;
    sig++;
    sig->cno = 26;
    sig->gnssId = 3;
    sig->quality = 7;
    sig->sigId = 6;
    sig->status = 41;
    sig->svId = 34;
    sig++;
    sig->cno = 40;
    sig->gnssId = 3;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 36;
    sig++;
    sig->cno = 31;
    sig->gnssId = 3;
    sig->quality = 7;
    sig->sigId = 6;
    sig->status = 41;
    sig->svId = 36;
    sig++;
    sig->cno = 36;
    sig->gnssId = 4;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 1;
    sig->svId = 11;
    sig++;
    sig->cno = 21;
    sig->gnssId = 4;
    sig->quality = 4;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 11;
    sig++;
    sig->cno = 44;
    sig->gnssId = 4;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 14;
    sig++;
    sig->cno = 30;
    sig->gnssId = 4;
    sig->quality = 7;
    sig->sigId = 2;
    sig->status = 41;
    sig->svId = 14;
    sig++;
    sig->cno = 38;
    sig->gnssId = 4;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 27;
    sig++;
    sig->cno = 0;
    sig->gnssId = 4;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 27;
    sig++;
    sig->cno = 44;
    sig->gnssId = 4;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 28;
    sig++;
    sig->cno = 0;
    sig->gnssId = 4;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 28;
    sig++;
    sig->cno = 42;
    sig->gnssId = 4;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 33;
    sig++;
    sig->cno = 0;
    sig->gnssId = 4;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 33;
    sig++;
    sig->cno = 43;
    sig->gnssId = 4;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 41;
    sig++;
    sig->cno = 0;
    sig->gnssId = 4;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 41;
    sig++;
    sig->cno = 43;
    sig->gnssId = 4;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 43;
    sig++;
    sig->cno = 0;
    sig->gnssId = 4;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 43;
    sig++;
    sig->cno = 43;
    sig->gnssId = 4;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 2;
    sig->svId = 58;
    sig++;
    sig->cno = 31;
    sig->gnssId = 6;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 1;
    sig->svId = 1;
    sig++;
    sig->cno = 0;
    sig->gnssId = 6;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 1;
    sig++;
    sig->cno = 29;
    sig->gnssId = 6;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 2;
    sig++;
    sig->cno = 0;
    sig->gnssId = 6;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 2;
    sig++;
    sig->cno = 35;
    sig->gnssId = 6;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 8;
    sig++;
    sig->cno = 0;
    sig->gnssId = 6;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 8;
    sig++;
    sig->cno = 0;
    sig->gnssId = 6;
    sig->quality = 1;
    sig->sigId = 0;
    sig->status = 1;
    sig->svId = 16;
    sig++;
    sig->cno = 0;
    sig->gnssId = 6;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 16;
    sig++;
    sig->cno = 19;
    sig->gnssId = 6;
    sig->quality = 3;
    sig->sigId = 0;
    sig->status = 1;
    sig->svId = 17;
    sig++;
    sig->cno = 0;
    sig->gnssId = 6;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 17;
    sig++;
    sig->cno = 36;
    sig->gnssId = 6;
    sig->quality = 7;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 23;
    sig++;
    sig->cno = 0;
    sig->gnssId = 6;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 23;
    sig++;
    sig->cno = 32;
    sig->gnssId = 6;
    sig->quality = 4;
    sig->sigId = 0;
    sig->status = 41;
    sig->svId = 24;
    sig++;
    sig->cno = 0;
    sig->gnssId = 6;
    sig->quality = 1;
    sig->sigId = 2;
    sig->status = 1;
    sig->svId = 24;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 0;
    sig->sigId = 240;
    sig->status = 0;
    sig->svId = 0;
    sig++;
    sig->cno = 208;
    sig->gnssId = 0;
    sig->quality = 233;
    sig->sigId = 0;
    sig->status = 8978;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 133;
    sig->quality = 40;
    sig->sigId = 0;
    sig->status = 27395;
    sig->svId = 1;
    sig++;
    sig->cno = 0;
    sig->gnssId = 33;
    sig->quality = 0;
    sig->sigId = 1;
    sig->status = 336;
    sig->svId = 133;
    sig++;
    sig->cno = 1;
    sig->gnssId = 107;
    sig->quality = 0;
    sig->sigId = 133;
    sig->status = 256;
    sig->svId = 33;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 0;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 128;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 0;
    sig->svId = 4;
    sig++;
    sig->cno = 15;
    sig->gnssId = 0;
    sig->quality = 35;
    sig->sigId = 0;
    sig->status = 389;
    sig->svId = 0;
    sig++;
    sig->cno = 236;
    sig->gnssId = 0;
    sig->quality = 18;
    sig->sigId = 0;
    sig->status = 34083;
    sig->svId = 0;
    sig++;
    sig->cno = 112;
    sig->gnssId = 1;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 0;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 2;
    sig->sigId = 0;
    sig->status = 1024;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 6;
    sig->quality = 0;
    sig->sigId = 1;
    sig->status = 62;
    sig->svId = 133;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 4352;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 0;
    sig->svId = 0;
    sig++;
    sig->cno = 35;
    sig->gnssId = 160;
    sig->quality = 133;
    sig->sigId = 18;
    sig->status = 1;
    sig->svId = 234;
    sig++;
    sig->cno = 235;
    sig->gnssId = 0;
    sig->quality = 18;
    sig->sigId = 48;
    sig->status = 34083;
    sig->svId = 0;
    sig++;
    sig->cno = 208;
    sig->gnssId = 1;
    sig->quality = 235;
    sig->sigId = 0;
    sig->status = 8978;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 133;
    sig->quality = 40;
    sig->sigId = 0;
    sig->status = 27395;
    sig->svId = 1;
    sig++;
    sig->cno = 0;
    sig->gnssId = 33;
    sig->quality = 0;
    sig->sigId = 1;
    sig->status = 336;
    sig->svId = 133;
    sig++;
    sig->cno = 1;
    sig->gnssId = 107;
    sig->quality = 0;
    sig->sigId = 133;
    sig->status = 10240;
    sig->svId = 33;
    sig++;
    sig->cno = 1;
    sig->gnssId = 243;
    sig->quality = 0;
    sig->sigId = 118;
    sig->status = 0;
    sig->svId = 186;
    sig++;
    sig->cno = 33;
    sig->gnssId = 100;
    sig->quality = 133;
    sig->sigId = 107;
    sig->status = 1;
    sig->svId = 7;
    sig++;
    sig->cno = 15;
    sig->gnssId = 0;
    sig->quality = 35;
    sig->sigId = 0;
    sig->status = 389;
    sig->svId = 0;
    sig++;
    sig->cno = 235;
    sig->gnssId = 0;
    sig->quality = 18;
    sig->sigId = 64;
    sig->status = 34083;
    sig->svId = 0;
    sig++;
    sig->cno = 52;
    sig->gnssId = 1;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 0;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 208;
    sig->sigId = 0;
    sig->status = 0;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 4;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 3328;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 0;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 0;
    sig->svId = 0;
    sig++;
    sig->cno = 107;
    sig->gnssId = 0;
    sig->quality = 33;
    sig->sigId = 0;
    sig->status = 389;
    sig->svId = 0;
    sig++;
    sig->cno = 234;
    sig->gnssId = 0;
    sig->quality = 18;
    sig->sigId = 176;
    sig->status = 34083;
    sig->svId = 0;
    sig++;
    sig->cno = 74;
    sig->gnssId = 1;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 19972;
    sig->svId = 0;
    sig++;
    sig->cno = 0;
    sig->gnssId = 133;
    sig->quality = 107;
    sig->sigId = 0;
    sig->status = 5121;
    sig->svId = 1;
    sig++;
    sig->cno = 0;
    sig->gnssId = 80;
    sig->quality = 0;
    sig->sigId = 127;
    sig->status = 2;
    sig->svId = 250;
    sig++;
    sig->cno = 0;
    sig->gnssId = 4;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 61440;
    sig->svId = 6;
    sig++;
    sig->cno = 0;
    sig->gnssId = 0;
    sig->quality = 0;
    sig->sigId = 0;
    sig->status = 0;
    sig->svId = 0;
    sig++;
    sig->cno = 33;
    sig->gnssId = 90;
    sig->quality = 133;
    sig->sigId = 107;
    sig->status = 1;
    sig->svId = 7;
    sig++;
    sig->cno = 186;
    sig->gnssId = 0;
    sig->quality = 118;
    sig->sigId = 242;
    sig->status = 1;
    sig->svId = 48;

    // Check array out of bounds
    ASSERT_TRUE( sig < &(gpsSig.sig[MAX_NUM_SAT_SIGNALS]) );


    nmea_gsv(g_ascii_buf, ASCII_BUF2, gpsSat, gpsSig);
    // printf("%s\n", g_ascii_buf);

    // cout << "buf size: " << buf.size() << "\n";
    // cout << buf;

    // gps_sat_t result = {};
    // int lastGSVmsg[2] = {};
    // int satCount = 0;
    // uint32_t cnoSum = 0;
    // uint32_t cnoCount = 0;
    // nmea_parse_gsv(buf.c_str(), buf.size(), &result, lastGSVmsg, &satCount, &cnoSum, &cnoCount);

}
#endif


#if 0
TEST(protocol_nmea, GSV)
{
    string buf;


    // GPS & SBAS        #msgs,msg#,numSV,  svid,elv,azm,cno, ..., signalId*checksum
    buf += "$GPGSV,6,1,14," "02,40,310,43," "08,07,324,31," "10,48,267,45," "15,37,053,45"      "*67\r\n";
    buf += "$GPGSV,6,2,14," "16,12,268,35," "18,69,078,41," "23,74,336,40," "24,15,111,37"      "*62\r\n";
    buf += "$GPGSV,6,3,14," "26,02,239,31," "27,35,307,38," "29,12,162,37," "32,14,199,39"      "*60\r\n";
    buf += "$GPGSV,6,4,14," "44,43,188,43," "46,40,206,43," "522,48,267,45," "527,37,053,26"    "*65\r\n";
    buf += "$GPGSV,6,5,14," "530,69,078,34," "535,74,336,34," "536,15,111,25," "538,02,239,18," "*64\r\n";
    buf += "$GPGSV,6,6,14," "541,12,162,21," "544,14,199,25," "539,35,307,27"                   "*64\r\n";

    // Galileo
    buf += "$GAGSV,1,1,04," "05,65,144,30," "09,39,052,30," "34,71,341,27," "36,46,105,30," "2*73\r\n";
    buf += "$GAGSV,1,1,04," "05,65,144,41," "09,39,052,43," "34,71,341,42," "36,46,105,39," "7*7E\r\n";
    // Beidou
    buf += "$GBGSV,2,1,08," "11,09,141,34," "14,52,047,44," "27,32,313,43," "28,80,263,44," "1*71\r\n";
    buf += "$GBGSV,2,2,08," "33,81,039,43," "41,43,230,42," "43,33,148,42," "58,,,44,"      "1*4E\r\n";
    buf += "$GBGSV,1,1,02," "11,09,141,16," "14,52,047,32,"                                 "B*0D\r\n";
    // QZSS
    buf += "$GQGSV,1,1,01," "02,,,30,"                                                      "1*65\r\n";
    // GLONASS
    buf += "$GLGSV,2,1,06," "65,85,260,33," "66,28,217,30," "72,36,034,35," "81,20,324,33," "1*75\r\n";
    buf += "$GLGSV,2,2,06," "87,47,127,35," "88,73,350,34,"                                 "1*75\r\n";
    buf += "$GLGSV,1,1,01," "87,47,127,20,"                                                 "3*41\r\n";
    buf += "$GLGSV,1,1,01," "80,01,343,,"                                                   "0*45\r\n";


    // GPS & SBAS        #msgs,msg#,numSV,  svid,elv,azm,cno, ... *checksum
    buf += "$GPGSV,4,1,14," "02,40,310,43," "08,07,324,31," "10,48,267,45," "15,37,053,45"  "*67\r\n";
    buf += "$GPGSV,4,2,14," "16,12,268,35," "18,69,078,41," "23,74,336,40," "24,15,111,37"  "*62\r\n";
    buf += "$GPGSV,4,3,14," "26,02,239,31," "27,35,307,38," "29,12,162,37," "32,14,199,39"  "*60\r\n";
    buf += "$GPGSV,4,4,14," "44,43,188,43," "46,40,206,43"                                  "*65\r\n";
    // Galileo
    buf += "$GAGSV,1,1,04," "05,65,144,30," "09,39,052,30," "34,71,341,27," "36,46,105,30"  "*73\r\n";
    buf += "$GAGSV,1,1,04," "05,65,144,41," "09,39,052,43," "34,71,341,42," "36,46,105,39"  "*7E\r\n";
    // Beidou
    buf += "$GBGSV,2,1,08," "11,09,141,34," "14,52,047,44," "27,32,313,43," "28,80,263,44"  "*71\r\n";
    buf += "$GBGSV,2,2,08," "33,81,039,43," "41,43,230,42," "43,33,148,42," "58,,,44"       "*4E\r\n";
    buf += "$GBGSV,1,1,02," "11,09,141,16," "14,52,047,32"                                  "*0D\r\n";
    // QZSS
    buf += "$GQGSV,1,1,01," "02,,,30 "                                                      "*65\r\n";
    // GLONASS
    buf += "$GLGSV,2,1,06," "65,85,260,33," "66,28,217,30," "72,36,034,35," "81,20,324,33 " "*75\r\n";
    buf += "$GLGSV,2,2,06," "87,47,127,35," "88,73,350,34"                                  "*75\r\n";
    buf += "$GLGSV,1,1,01," "87,47,127,20"                                                  "*41\r\n";
    buf += "$GLGSV,1,1,01," "80,01,343,"                                                    "*45\r\n";

    gps_sat_t gpsSat = {};
    gpsSat.numSats = 31;
    gpsSat.timeOfWeekMs = 436693200;
    gps_sat_sv_t *sat = &(gpsSat.sat[0]);
    sat->azim = 310;
    sat->cno = 43;
    sat->elev = 40;
    sat->gnssId = 1;
    sat->status = 95;
    sat->svId = 2;
    sat++;
    sat->azim = 324;
    sat->cno = 45;
    sat->elev = 07;
    sat->gnssId = 1;
    sat->status = 95;
    sat->svId = 8;
    sat++;
    sat->azim = 267;
    sat->cno = 45;
    sat->elev = 48;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 10;
    sat++;
    sat->azim = 53;
    sat->cno = 45;
    sat->elev = 37;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 15;
    sat++;
    sat->azim = 268;
    sat->cno = 35;
    sat->elev = 12;
    sat->gnssId = 1;
    sat->status = 95;
    sat->svId = 16;
    sat++;
    sat->azim = 78;
    sat->cno = 41;
    sat->elev = 69;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 18;
    sat++;
    sat->azim = 336;
    sat->cno = 40;
    sat->elev = 74;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 23;
    sat++;
    sat->azim = 111;
    sat->cno = 37;
    sat->elev = 15;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 24;
    sat++;
    sat->azim = 239;
    sat->cno = 31;
    sat->elev = 02;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 26;
    sat++;
    sat->azim = 307;
    sat->cno = 38;
    sat->elev = 35;
    sat->gnssId = 1;
    sat->status = 95;
    sat->svId = 27;
    sat++;
    sat->azim = 162;
    sat->cno = 37;
    sat->elev = 12;
    sat->gnssId = 1;
    sat->status = 31;
    sat->svId = 29;
    sat++;
    sat->azim = 199;
    sat->cno = 39;
    sat->elev = 14;
    sat->gnssId = 1;
    sat->status = 95;
    sat->svId = 32;
    sat++;
    sat->azim = 188;
    sat->cno = 43;
    sat->elev = 43;
    sat->gnssId = 2;
    sat->status = 95;
    sat->svId = 131;
    sat++;
    sat->azim = 206;
    sat->cno = 43;
    sat->elev = 40;
    sat->gnssId = 2;
    sat->status = 95;
    sat->svId = 133;
    sat++;
    sat->azim = 173;
    sat->cno = 0;
    sat->elev = 43;
    sat->gnssId = 2;
    sat->status = 1;
    sat->svId = 138;
    sat++;
    sat->azim = 145;
    sat->cno = 41;
    sat->elev = 65;
    sat->gnssId = 3;
    sat->status = 31;
    sat->svId = 5;
    sat++;
    sat->azim = 53;
    sat->cno = 43;
    sat->elev = 39;
    sat->gnssId = 3;
    sat->status = 31;
    sat->svId = 9;
    sat++;
    sat->azim = 340;
    sat->cno = 42;
    sat->elev = 71;
    sat->gnssId = 3;
    sat->status = 31;
    sat->svId = 34;
    sat++;
    sat->azim = 104;
    sat->cno = 40;
    sat->elev = 47;
    sat->gnssId = 3;
    sat->status = 31;
    sat->svId = 36;
    sat++;
    sat->azim = 141;
    sat->cno = 36;
    sat->elev = 9;
    sat->gnssId = 4;
    sat->status = 23;
    sat->svId = 11;
    sat++;
    sat->azim = 47;
    sat->cno = 44;
    sat->elev = 52;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 14;
    sat++;
    sat->azim = 313;
    sat->cno = 38;
    sat->elev = 31;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 27;
    sat++;
    sat->azim = 267;
    sat->cno = 44;
    sat->elev = 79;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 28;
    sat++;
    sat->azim = 40;
    sat->cno = 42;
    sat->elev = 82;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 33;
    sat++;
    sat->azim = 230;
    sat->cno = 43;
    sat->elev = 43;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 41;
    sat++;
    sat->azim = 148;
    sat->cno = 43;
    sat->elev = 34;
    sat->gnssId = 4;
    sat->status = 31;
    sat->svId = 43;
    sat++;
    sat->azim = 0;
    sat->cno = 43;
    sat->elev = 0;
    sat->gnssId = 4;
    sat->status = 39;
    sat->svId = 58;
    sat++;
    sat->azim = 252;
    sat->cno = 31;
    sat->elev = 85;
    sat->gnssId = 6;
    sat->status = 23;
    sat->svId = 1;
    sat++;
    sat->azim = 217;
    sat->cno = 29;
    sat->elev = 28;
    sat->gnssId = 6;
    sat->status = 31;
    sat->svId = 2;
    sat++;
    sat->azim = 34;
    sat->cno = 35;
    sat->elev = 37;
    sat->gnssId = 6;
    sat->status = 31;
    sat->svId = 8;
    sat++;
    sat->azim = 344;
    sat->cno = 0;
    sat->elev = 1;
    sat->gnssId = 6;
    sat->status = 17;
    sat->svId = 16;
    sat++;
    sat->azim = 324;
    sat->cno = 19;
    sat->elev = 19;
    sat->gnssId = 6;
    sat->status = 19;
    sat->svId = 17;
    sat++;
    sat->azim = 126;
    sat->cno = 36;
    sat->elev = 48;
    sat->gnssId = 6;
    sat->status = 31;
    sat->svId = 23;
    sat++;
    sat->azim = 349;
    sat->cno = 32;
    sat->elev = 72;
    sat->gnssId = 6;
    sat->status = 28;
    sat->svId = 24;
    sat++;
    sat->azim = 374;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 40;
    sat->status = 0;
    sat->svId = 243;
    sat++;
    sat->azim = 374;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 0;
    sat->status = 0;
    sat->svId = 239;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 0;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 1;
    sat->elev = 1;
    sat->gnssId = 4;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 2;
    sat->elev = 0;
    sat->gnssId = 0;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 3;
    sat->cno = 0;
    sat->elev = 4;
    sat->gnssId = 7;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 72;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 1;
    sat->elev = 0;
    sat->gnssId = 1;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 0;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 0;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 82;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 1;
    sat->elev = 18;
    sat->gnssId = 160;
    sat->status = 0;
    sat->svId = 234;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 4;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 1;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 0;
    sat->elev = 0;
    sat->gnssId = 82;
    sat->status = 0;
    sat->svId = 0;
    sat++;
    sat->azim = 0;
    sat->cno = 127;
    sat->elev = 0;
    sat->gnssId = 42;
    sat->status = 0;
    sat->svId = 66;

    // Check array out of bounds
    ASSERT_TRUE( sat != &(gpsSat.sat[MAX_NUM_SATELLITES]) );



    nmea_gsv(g_ascii_buf, ASCII_BUF2, gpsSat);
    // printf("%s\n", g_ascii_buf);

    // cout << "buf size: " << buf.size() << "\n";
    // cout << buf;

    // gps_sat_t result = {};
    // int lastGSVmsg[2] = {};
    // int satCount = 0;
    // uint32_t cnoSum = 0;
    // uint32_t cnoCount = 0;
    // nmea_parse_gsv(buf.c_str(), buf.size(), &result, lastGSVmsg, &satCount, &cnoSum, &cnoCount);

}
#endif


