if(WIN32)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(IS_SDK_BUILD_DIR "${IS_SDK_DIR}/build-debug")
    else()
        set(IS_SDK_BUILD_DIR "${IS_SDK_DIR}/build-release")
    endif()
else()
    set(IS_SDK_BUILD_DIR "${IS_SDK_DIR}/build")
endif()

find_library(SDK_LIBRARY_PATH InertialSenseSDK PATHS ${IS_SDK_BUILD_DIR})

if(NOT SDK_LIBRARY_PATH AND NOT TARGET InertialSenseSDK)
    # InertialSenseSDK library not prebuilt and not already included in project.  Include it in this project.
    add_subdirectory(${IS_SDK_DIR} InertialSenseSDK)
    message("InertialSenseSDK library NOT FOUND.  Including SDK source in project.")
else()
    link_directories(${IS_SDK_BUILD_DIR})
    message("Using InertialSenseSDK library prebuilt at: ${SDK_LIBRARY_PATH}")
endif()