/**
 * @file MyCustomSerialPortFactory.h 
 * @brief ${BRIEF_DESC}
 * 
 * @remark Based upon the SDK src/PortFactory.h
 * @author TylerS
 * @copyright Copyright (c) 2026 Inertial Sense, Inc. All rights reserved.
 */

/** @note
 * These double-asterisk comments are Doxygen style, included in documentation 
 * generated by that tool if run, and found throughout the code in this
 * example to guide users through the process of creating and using custom ports
 */

#ifndef MY_CUSTOM_SERIAL_PORT_FACTORY_H
#define MY_CUSTOM_SERIAL_PORT_FACTORY_H

#ifdef __cplusplus

#include "core/base_port.h"
#include "core/msg_logger.h"
#include "ISConstants.h"

#include "serialPort.h"

/** Include the header file for the abstract class PortFactory.h
 */
#include "PortFactory.h"

/** Create a custom child class that inherits from PortFactory 
 */
class MyCustomSerialPortFactory : public PortFactory {
public:
    /** (optional) Default port config options for the factory, customized to the type of port you create */
    struct {
        int defaultBaudRate = BAUDRATE_921600;
        bool defaultBlocking = false;
    } portOptions = {};

    /** We need a way to get an instance of the singleton port factory */
    static MyCustomSerialPortFactory& getInstance() {
        static MyCustomSerialPortFactory instance;
        return instance;
    }

    /** Remove certain constructors/operators, because we're a singleton... */
    MyCustomSerialPortFactory(MyCustomSerialPortFactory const &) = delete;
    MyCustomSerialPortFactory& operator=(MyCustomSerialPortFactory const&) = delete;

    /**
     * These four functions will be required for your implementation, can be 
     * defined in your .cpp file for this class 
     */
    void locatePorts(std::function<void(PortFactory*, uint16_t, std::string)> portCallback, const std::string& pattern, uint16_t pType) override;
    bool validatePort(const std::string& pName, uint16_t pType = 0) override;
    port_handle_t bindPort(const std::string& pName, uint16_t pType = 0) override;
    bool releasePort(port_handle_t port) override;

    /** (optional) Functions for setting the port config options, customized to the type of port you create */
    MyCustomSerialPortFactory& setBaudRate(uint32_t baud) { portOptions.defaultBaudRate = baud; return *this; }
    MyCustomSerialPortFactory& setBlocking(bool block) { portOptions.defaultBlocking = block; return *this; }

private:
    /** Make these private for our singleton pattern */
    MyCustomSerialPortFactory() = default;
    ~MyCustomSerialPortFactory() = default;

    /**
     * A static function which is used to report errors that occur on a port created by this factory
     * @param port the port the error occurred on
     * @param errCode the error code (usually errno) of the error that occurred
     * @param errMsg an optional string message which describes the error the occurred
     * @return
     */
    static int onPortError(port_handle_t port, int errCode, const char *errMsg);

    std::vector<std::string> portNames = {};

    /**
     * An internal static function which identifies all available serial ports on the host device. It populates a referenced
     * std::vector<std::string> with their names, as suitable identifiers. This does NOT do any port_handle allocation, validation,
     * or other operations necessary to USE the port - it merely identifies them.
     * @param portNames a reference to a vector of strings which will be cleared, and populated with UART/Serial ports known to
     *  the host operating system.
     * @return the number of port names populated into the vector.
     */
    static int getComPorts(std::vector<std::string>& portNames);


#if PLATFORM_IS_LINUX
    static std::string get_driver__linux(const std::string& tty);
    static void register_comport__linux(std::vector<std::string>& comList, std::vector<std::string>& comList8250, const std::string& dir);
    static void probe_serial8250_comports__linux(std::vector<std::string>& comList, std::vector<std::string> comList8250);

    static bool validate_port__linux(uint16_t pType, const std::string& pName);
#elif PLATFORM_IS_WINDOWS
#endif

    // THESE ARE LOCALIZED HELPER FUNCTIONS to provide basic functionality that is not normally provided by the original SerialPort/SerialPortPlatform implementation
    // TODO: at some point, these should be moved into the implementation directly, and removed from the factory
    static int validate_port(port_handle_t port) { return MyCustomSerialPortFactory::getInstance().validatePort(portName(port), portType(port)); }
    static int open_port(port_handle_t port) { return serialPortOpen(port, SERIAL_PORT(port)->portName, SERIAL_PORT(port)->baudRate, SERIAL_PORT(port)->blocking); }

};


#endif //  __cplusplus

#endif // MY_CUSTOM_SERIAL_PORT_FACTORY_H
