.PHONY: clean All

All:
	@echo "----------Building project:[ cltool - Debug ]----------"
	@$(MAKE) -f  "cltool.mk"
clean:
	@echo "----------Cleaning project:[ cltool - Debug ]----------"
	@$(MAKE) -f  "cltool.mk" clean
