/**
 * @file CustomVirtualPortFactory.cpp
 * @brief ${BRIEF_DESC}
 * 
 * @remark Based upon the SDK src/PortFactory.cpp
 * @author TylerS
 * @copyright Copyright (c) 2026 Inertial Sense, Inc. All rights reserved.
 */

/** @note
 * These double-asterisk comments are Doxygen style, included in documentation 
 * generated by that tool if run, and found throughout the code in this
 * example to guide users through the process of creating and using custom ports
 */

/** Include the header file for your child port factory class derived from master PortFactory.h
 */
#include "CustomVirtualPortFactory.h"

/** Include C++ libraries for use by your custom port class member functions defined here
 */
#include <string>
#include <vector>
#include <regex>

/** Include utility functions for use by your custom port class member functions defined here
 */
#include "util/util.h"
#include "ISUtilities.h"

/**
 * Include the PortManager for building and maintaining a list of all ports by name 
 */
#include "PortManager.h"

/**
 * Include any of your own custom application port definition headers, the lower-level
 * code that defines the interface used by this custom port factory
 */
//#include "serialPort.h"
//#include "serialPortPlatform.h"


/**
 * @brief Required minimum method, validates name and type, locates and instantiates new port
 * 
 */
port_handle_t CustomVirtualPortFactory::bindPort(const std::string& pName, uint16_t pType) {
    if (!validatePort(pName, pType))
        return nullptr;

    printf("bind pName: %s, size %lu\r\n", pName.c_str(), pName.length());

    
    /** In this example we use a virtual port, so there is no baud rate or blocking to set
     */
    //serial_port_t* serialPort = new serial_port_t;
    //port_handle_t port = (port_handle_t)serialPort;
    
    //g_testPorts given by TESTn_PORT is an array of test_port_t, port0 is a loopback port
    test_port_t* testPort = TEST0_PORT; 
    port_handle_t port = (port_handle_t) testPort;
    
    //*serialPort = {};
    *testPort = {};
    //serialPortInit(port, (uint16_t)PortManager::getInstance().getPortCount(), (pType | PORT_TYPE__UART | PORT_TYPE__COMM), 0);

    /** This init routine assigns the base port functions of the underlying port implementation
     */
    printf("testPort name: %s\r\n", testPort->name);

    initTestPorts();
    printf("testPort name: %s\r\n", testPort->name);

    //strncpy(serialPort->portName, pName.c_str(), pName.length());
    //strncpy(reinterpret_cast<char*>(testPort->name), pName.c_str(), pName.length());

    printf("testPort name: %s\r\n", testPort->name);

    // // serialPort->base.portOpen = CustomSerialPortFactory::open_port;
    // serialPort->base.portValidate = CustomSerialPortFactory::validate_port;
    // serialPort->pfnError = CustomSerialPortFactory::onPortError;
    testPort->base.portValidate = CustomVirtualPortFactory::validate_port;

    // serialPort->baudRate = portOptions.defaultBaudRate;
    // serialPort->blocking = portOptions.defaultBlocking;

    portValidate(port);


    printf("testPort name: %s\r\n", testPort->name);

    
    //tms not linking log_more_debug(IS_LOG_PORT_FACTORY, "Allocated new serial port '%s'", portName(port));
    return port;
}


/**
 * @brief Required minimum method, clears memory associated with port created in bindPort
 * 
 */
bool CustomVirtualPortFactory::releasePort(port_handle_t port) {
    if (!port)
        return false;

    //tms not linking log_more_debug(IS_LOG_PORT_FACTORY, "Releasing serial port '%s'", ((serial_port_t*)port)->portName);
 
    /** In this example we use a virtual port with the static object, so there is no memory to free, only clear
     */
    memset(port, 0, sizeof(test_port_t));

    /** If you allocated your port object on the heap, free the memory (delete) here
     */
    //delete (serial_port_t*)port;

    return true;
}

/**
 * @brief Required minimum method, checks port name/type for viability
 * 
 */
bool CustomVirtualPortFactory::validatePort(const std::string& pName, uint16_t pType) {
    /** Check port type to make sure it is allowed, in this case both these types
     */
    if (pType != (PORT_TYPE__LOOPBACK | PORT_TYPE__COMM) )
        return false;   // we can only validate this port type - all others fail
    
    /** Add here any other custom validation that could/should be done on this port type
     */

    return true;
}

/**
 * @brief Required minimum method, looks for matching name to port and calls portCallback
 * 
 */
void CustomVirtualPortFactory::locatePorts(std::function<void(PortFactory*, uint16_t, std::string)> portCallback, const std::string& pattern, uint16_t pType) {
    std::regex matchPattern(pattern);
    getComPorts(portNames);
    for (auto& name : portNames) {
        auto match = std::regex_match(name, matchPattern);
        if (validatePort(name, PORT_TYPE__LOOPBACK) && match)
            portCallback(this, PORT_TYPE__LOOPBACK, name);
    }
}

int CustomVirtualPortFactory::onPortError(port_handle_t port, int errCode, const char *errMsg) {
    // const char* portStr = portName(port);
    // const char* safeErrMsg = errMsg ? errMsg : "";

    static int lastErrorCode = 0;       // the previous error code
    static int repeatCount = 0;         // number of time the same code has repeated
    static uint32_t lastErrorMs = 0;    // the time when the lastErrorCode changed to the current error code

    if (errCode != lastErrorCode) {
        repeatCount = 0;
        lastErrorMs = current_timeMs();
        lastErrorCode = errCode;

        // General errors should already be reported by the underlying port implementation (if IS_LOG_PORT is configured)
        // log_error(IS_LOG_PORT_FACTORY, "%s :: Error %d : %s", portStr, errCode, safeErrMsg);
    } else {
        // Split the printf into two calls (helps avoid inlining inference)
        // log_error(IS_LOG_PORT_FACTORY, "%s :: Error %d : %s (%d count)", portStr, errCode, safeErrMsg, ++repeatCount);

        if ((current_timeMs() - lastErrorMs > 30000) && (repeatCount++ >= 10)){
            // any error which repeats for more than 30 seconds, and more than 10 times, close & invalidate
            portClose(port);
            portInvalidate(port);
            return 0;
        }
    }

    // decide which of these should result in a port-closure, vs a port invalid, vs nothing...
    switch (errCode) {
        // close but don't invalidate
        case EIO:       /* I/O error */
        case ENXIO:     /* No such device or address */
        case E2BIG:     /* Argument list too long */
        case ENOEXEC:   /* Exec format error */
        case EBADF:     /* Bad file number */
        case ECHILD:    /* No child processes */
        case ENOMEM:    /* Out of memory */
        case EACCES:    /* Permission denied */
        case EFAULT:    /* Bad address */
        case ENFILE:    /* File table overflow */
        case EMFILE:    /* Too many open files */
        case EFBIG:     /* File too large */
        case ENOSPC:    /* No space left on device */
        case ESPIPE:    /* Illegal seek */
        case EROFS:     /* Read-only file system */
        case EMLINK:    /* Too many links */
            portClose(port);
            break;

            // close and invalidate
        case ENOENT:    /* No such file or directory */
        case ESRCH:     /* No such process */
        case ENODEV:    /* No such device */
        case ENOTDIR:   /* Not a directory */
        case EISDIR:    /* Is a directory */
#if PLATFORM_IS_LINUX
        case ENOTBLK:   /* Block device required */
#endif
        case EPIPE:     /* Broken pipe */
            portClose(port);
            portInvalidate(port);
            break;


        // ignore
        case EBUSY:     /* Device or resource busy */
        case EAGAIN:    /* Try again */
        case EPERM:     /* Operation not permitted */
        case EINTR:     /* Interrupted system call */

        case EEXIST:    /* File exists */
        case EXDEV:     /* Cross-device link */
        case EINVAL:    /* Invalid argument */
        case ENOTTY:    /* Not a typewriter */
        case ETXTBSY:   /* Text file busy */
        case EDOM:      /* Math argument out of domain of func */
        case ERANGE:    /* Math result not representable */
        default:
            // do nothing (try again??)
            break;
    }
    return 0;
}

/**
 * Populates a vector of string identifiers for all available Serial/TTY/UART devices on the host system.
 * For this example, it will be a number of virtual ports defined in the data_sets.h header used by the 
 * test_serial_utils definitions.
 * This does not open, access, or configure the devices, nor does it make any guarantee about the availability
 * of the ports (only that the OS has registered/enumerated it).
 * @param portNames a reference to a vector of strings, which will be populated with names identifiers of available ports
 * @return the number of ports found on the host
 */
int CustomVirtualPortFactory::getComPorts(std::vector<std::string>& portNames)
{
    portNames.clear();
    portNames.resize(NUM_COM_PORTS);

    // Populate the vector using a generator
    int i = 0;
    
    // Generate each string with arbitrary but unique identifying names
    for (auto& str : portNames) {
        str = "tp" + std::to_string(i) + "\0";
        ++i;
    }

    return portNames.size();
}


#if PLATFORM_IS_LINUX
#include <fcntl.h>
#include <sys/ioctl.h>
#include <linux/serial.h>


#endif // #if PLATFORM_IS_LINUX
