/**
 * @file CustomVirtualPortFactory.cpp
 * @brief ${BRIEF_DESC}
 * 
 * @remark Based upon the SDK src/PortFactory.cpp
 * @author TylerS
 * @copyright Copyright (c) 2026 Inertial Sense, Inc. All rights reserved.
 */

/** 
 * @note These double-asterisk comments are Doxygen style, included in documentation 
 * generated by that tool if run, and found throughout the code in this
 * example to guide users through the process of creating and using custom ports
 */

/** STEP 2: Include C++ libraries for use by your custom port class member functions defined here
 */
#include <vector>
#include <regex>

/** Include the header file for your child port factory class derived from parent PortFactory.h
 */
#include "CustomVirtualPortFactory.h"

/** Include utility functions for use by your custom port class member functions defined here
 */
//for example, #include "util/util.h"
#include "ISUtilities.h"

/**
 * Include the PortManager if desired for building and maintaining a list of all ports by name 
 */
//#include "PortManager.h"


/** STEP 3
 * @brief  Required minimum method, validates name and type, locates and/or instantiates new port
 */
port_handle_t CustomVirtualPortFactory::bindPort(const std::string& pName, uint16_t pType) {
    if (!validatePort(pName, pType))
        return nullptr;
   
    /** In this example we use a virtual port, so there is no baud rate or blocking to set; our port is defined by
     *  CustomVirtualPort; defined g_customPorts given by TESTn_PORT is an array of custom_port_t, 0 and 1 are loopback ports
     */
    custom_port_t* customPort;
    if (pName == "TEST0") {
        customPort = TEST0_PORT;
    }
    else if (pName == "TEST1") {
        customPort = TEST1_PORT;
    }
    else
        return nullptr;

    /** Need a port_handle_t reference to our port to use for our own validation and to return from bind */
    port_handle_t port = (port_handle_t) customPort;
    *customPort = {};

    /** This init routine assigns the base port functions of the underlying port implementation
     */
    initCustomPorts();

    /** Open and validate and configure the port as needed for the port implementation here; in this virtual port
     * example, do not need to open or configure
     */
    customPort->base.portValidate = CustomVirtualPortFactory::validate_port;
    portValidate(port);
       
    log_msg(IS_LOG_PORT_FACTORY, IS_LOG_LEVEL_INFO, "Allocated new comm port '%s'", portName(port));
    return port;
}


/**
 * @brief Required minimum method, clears memory associated with port created in bindPort
 * 
 */
bool CustomVirtualPortFactory::releasePort(port_handle_t port) {
    if (!port)
        return false;

    log_msg(IS_LOG_PORT_FACTORY, IS_LOG_LEVEL_INFO, "Releasing comm port '%s'", portName(port) );

    /** If you allocated your port object on the heap, free the memory (delete) here;
     * In this example we use a virtual port with the static object, so there is no memory to free, only clear
     */
    //for example, delete (serial_port_t*)port;
    memset(port, 0, sizeof(custom_port_t));

    return true;
}

/**
 * @brief Required minimum method, checks port name/type for viability
 * 
 */
bool CustomVirtualPortFactory::validatePort(const std::string& pName, uint16_t pType) {
    /** Check port type to make sure it is allowed, in this case both these types
     */
    if (pType != (PORT_TYPE__LOOPBACK | PORT_TYPE__COMM) )           
            return false;   // we can only validate this port type - all others fail
        
    /** Add here any other custom validation that could/should be done on this port type
     */
     
    return true;
}

/**
 * @brief Required minimum method, looks for matching name to port and calls portCallback
 * 
 */
void CustomVirtualPortFactory::locatePorts(std::function<void(PortFactory*, uint16_t, std::string)> portCallback, const std::string& pattern, uint16_t pType) {
    std::regex matchPattern(pattern);

    log_msg(IS_LOG_PORT_FACTORY, IS_LOG_LEVEL_INFO, "Locating ports with regex pattern '%s'", pattern.c_str());

    /** Call user implemented function to populate portNames as present on system; can use count returned if desired
     */
    getComPorts(portNames);

    /** For each port that is found by name matching search pattern, validate it and call user-defined callback function
     */
    for (auto& name : portNames) {
        auto match = std::regex_match(name, matchPattern);
        if (validatePort(name, (PORT_TYPE__LOOPBACK | PORT_TYPE__COMM) ) && match) {
            portCallback(this, (PORT_TYPE__LOOPBACK | PORT_TYPE__COMM), name);
        }
    }
}


/**
 * Populates a vector of string identifiers for all available virtual ports from test_serial_utils.
 * For this example, it will be a number of virtual ports defined in the data_sets.h header used by the 
 * test_serial_utils definitions.
 * @param portNames a reference to a vector of strings, which will be populated with names identifiers of available ports
 * @return the number of ports found on the host
 */
int CustomVirtualPortFactory::getComPorts(std::vector<std::string>& portNames)
{
    portNames.clear();
    portNames.resize(NUM_COM_PORTS);

    // The size of the custom_port_t name is a magic number in the declaration; derive it rather than
    // insert the same number in case it changes    
    size_t nlen = sizeof( ((custom_port_t*)0)->name );
        
    // Populate the vector using index into global test port array
    int i = 0;
    
    // Generate each string with the unique identifying names the underlying test port implementation dictates;
    // won't assume the test port names are null-terminated
    for (auto& str : portNames) {
        str = std::string( reinterpret_cast<const char*>(g_customPorts[i].name), nlen );
        log_msg(IS_LOG_PORT_FACTORY, IS_LOG_LEVEL_INFO, "Found port '%s'", str.c_str());
        ++i;
    }

    return portNames.size();
} //getComPorts

