/**
 * @file CustomVirtualPortFactory.cpp
 * @brief ${BRIEF_DESC}
 * 
 * @remark Based upon the SDK src/PortFactory.cpp
 * @author TylerS
 * @copyright Copyright (c) 2026 Inertial Sense, Inc. All rights reserved.
 */

/** 
 * @note These double-asterisk comments are Doxygen style, included in documentation 
 * generated by that tool if run, and found throughout the code in this
 * example to guide users through the process of creating and using custom ports
 */

/** Include C++ libraries for use by your custom port class member functions defined here
 */
#include <string>
#include <vector>
#include <regex>

/** Include the header file for your child port factory class derived from parent PortFactory.h
 */
#include "CustomVirtualPortFactory.h"

/** Include utility functions for use by your custom port class member functions defined here
 */
//for example, #include "util/util.h"
#include "ISUtilities.h"

/**
 * Include the PortManager for building and maintaining a list of all ports by name 
 */
//#include "PortManager.h"

/**
 * Include any of your own custom application port definition headers, the lower-level
 * code that defines the interface used by this custom port factory
 */
//for example, #include "serialPort.h"
//for example, #include "serialPortPlatform.h"


/**
 * @brief Required minimum method, validates name and type, locates and/or instantiates new port
 * 
 */
port_handle_t CustomVirtualPortFactory::bindPort(const std::string& pName, uint16_t pType) {
    if (!validatePort(pName, pType))
        return nullptr;
   
    /** In this example we use a virtual port, so there is no baud rate or blocking to set; our port is defined by
     *  test_serial_utils; defined g_testPorts given by TESTn_PORT is an array of test_port_t, 0 and 1 are loopback ports
     */
    test_port_t* testPort;
    if (pName == "TEST0") {
        testPort = TEST0_PORT;
    }
    else if (pName == "TEST1") {
        testPort = TEST1_PORT;
    }
    else
        return nullptr;
            
    port_handle_t port = (port_handle_t) testPort;   
    *testPort = {};

    /** This init routine assigns the base port functions of the underlying port implementation
     */
    initTestPorts();

    /** Open and validate and configure the port as needed for the port implementation here; in this virtual port
     * example, do not need to open or configure
     */
    // // serialPort->base.portOpen = CustomSerialPortFactory::open_port;
    // serialPort->base.portValidate = CustomSerialPortFactory::validate_port;
    // serialPort->pfnError = CustomSerialPortFactory::onPortError;
    testPort->base.portValidate = CustomVirtualPortFactory::validate_port;
    portValidate(port);
       
    log_msg(IS_LOG_PORT_FACTORY, IS_LOG_LEVEL_INFO, "Allocated new comm port '%s'", portName(port));
    return port;
}


/**
 * @brief Required minimum method, clears memory associated with port created in bindPort
 * 
 */
bool CustomVirtualPortFactory::releasePort(port_handle_t port) {
    if (!port)
        return false;

    log_msg(IS_LOG_PORT_FACTORY, IS_LOG_LEVEL_INFO, "Releasing comm port '%s'", portName(port) );

    /** If you allocated your port object on the heap, free the memory (delete) here;
     * In this example we use a virtual port with the static object, so there is no memory to free, only clear
     */
    //for example, delete (serial_port_t*)port;
    memset(port, 0, sizeof(test_port_t));

    return true;
}

/**
 * @brief Required minimum method, checks port name/type for viability
 * 
 */
bool CustomVirtualPortFactory::validatePort(const std::string& pName, uint16_t pType) {
    /** Check port type to make sure it is allowed, in this case both these types
     */
    if (pType != (PORT_TYPE__LOOPBACK | PORT_TYPE__COMM) )           
            return false;   // we can only validate this port type - all others fail
        
    /** Add here any other custom validation that could/should be done on this port type
     */
     
    return true;
}

/**
 * @brief Required minimum method, looks for matching name to port and calls portCallback
 * 
 */
void CustomVirtualPortFactory::locatePorts(std::function<void(PortFactory*, uint16_t, std::string)> portCallback, const std::string& pattern, uint16_t pType) {
    std::regex matchPattern(pattern);

    log_msg(IS_LOG_PORT_FACTORY, IS_LOG_LEVEL_INFO, "Locating ports with regex pattern '%s'", pattern.c_str());

    /** Call user implemented function to populate portNames as present on system; can use count returned if desired
     */
    getComPorts(portNames);

    /** For each port that is found by name matching search pattern, validate it and call user-defined callback function
     */
    for (auto& name : portNames) {
        auto match = std::regex_match(name, matchPattern);
        if (validatePort(name, (PORT_TYPE__LOOPBACK | PORT_TYPE__COMM) ) && match) {
            portCallback(this, (PORT_TYPE__LOOPBACK | PORT_TYPE__COMM), name);
        }
    }
}

int CustomVirtualPortFactory::onPortError(port_handle_t port, int errCode, const char *errMsg) {
    // const char* portStr = portName(port);
    // const char* safeErrMsg = errMsg ? errMsg : "";

    static int lastErrorCode = 0;       // the previous error code
    static int repeatCount = 0;         // number of time the same code has repeated
    static uint32_t lastErrorMs = 0;    // the time when the lastErrorCode changed to the current error code

    if (errCode != lastErrorCode) {
        repeatCount = 0;
        lastErrorMs = current_timeMs();
        lastErrorCode = errCode;

        // General errors should already be reported by the underlying port implementation (if IS_LOG_PORT is configured)
        // log_error(IS_LOG_PORT_FACTORY, "%s :: Error %d : %s", portStr, errCode, safeErrMsg);
    } else {
        // Split the printf into two calls (helps avoid inlining inference)
        // log_error(IS_LOG_PORT_FACTORY, "%s :: Error %d : %s (%d count)", portStr, errCode, safeErrMsg, ++repeatCount);

        if ((current_timeMs() - lastErrorMs > 30000) && (repeatCount++ >= 10)){
            // any error which repeats for more than 30 seconds, and more than 10 times, close & invalidate
            portClose(port);
            portInvalidate(port);
            return 0;
        }
    }

    // decide which of these should result in a port-closure, vs a port invalid, vs nothing...
    switch (errCode) {
        // close but don't invalidate
        case EIO:       /* I/O error */
        case ENXIO:     /* No such device or address */
        case E2BIG:     /* Argument list too long */
        case ENOEXEC:   /* Exec format error */
        case EBADF:     /* Bad file number */
        case ECHILD:    /* No child processes */
        case ENOMEM:    /* Out of memory */
        case EACCES:    /* Permission denied */
        case EFAULT:    /* Bad address */
        case ENFILE:    /* File table overflow */
        case EMFILE:    /* Too many open files */
        case EFBIG:     /* File too large */
        case ENOSPC:    /* No space left on device */
        case ESPIPE:    /* Illegal seek */
        case EROFS:     /* Read-only file system */
        case EMLINK:    /* Too many links */
            portClose(port);
            break;

            // close and invalidate
        case ENOENT:    /* No such file or directory */
        case ESRCH:     /* No such process */
        case ENODEV:    /* No such device */
        case ENOTDIR:   /* Not a directory */
        case EISDIR:    /* Is a directory */
#if PLATFORM_IS_LINUX
        case ENOTBLK:   /* Block device required */
#endif
        case EPIPE:     /* Broken pipe */
            portClose(port);
            portInvalidate(port);
            break;


        // ignore
        case EBUSY:     /* Device or resource busy */
        case EAGAIN:    /* Try again */
        case EPERM:     /* Operation not permitted */
        case EINTR:     /* Interrupted system call */

        case EEXIST:    /* File exists */
        case EXDEV:     /* Cross-device link */
        case EINVAL:    /* Invalid argument */
        case ENOTTY:    /* Not a typewriter */
        case ETXTBSY:   /* Text file busy */
        case EDOM:      /* Math argument out of domain of func */
        case ERANGE:    /* Math result not representable */
        default:
            // do nothing (try again??)
            break;
    }
    return 0;
}

/**
 * Populates a vector of string identifiers for all available virtual ports from test_serial_utils.
 * For this example, it will be a number of virtual ports defined in the data_sets.h header used by the 
 * test_serial_utils definitions.
 * @param portNames a reference to a vector of strings, which will be populated with names identifiers of available ports
 * @return the number of ports found on the host
 */
int CustomVirtualPortFactory::getComPorts(std::vector<std::string>& portNames)
{
    portNames.clear();
    portNames.resize(NUM_COM_PORTS);

    // The size of the test_port_t name is a magic number in the declaration; derive it rather than
    // insert the same number in case it changes    
    size_t nlen = sizeof( ((test_port_t*)0)->name );
        
    // Populate the vector using index into global test port array
    int i = 0;
    
    // Generate each string with the unique identifying names the underlying test port implementation dictates;
    // won't assume the test port names are null-terminated
    for (auto& str : portNames) {
        str = std::string( reinterpret_cast<const char*>(g_testPorts[i].name), nlen );
        log_msg(IS_LOG_PORT_FACTORY, IS_LOG_LEVEL_INFO, "Found port '%s'", str.c_str());
        ++i;
    }

    return portNames.size();
} //getComPorts

