.PHONY: clean All

All:
	@echo "----------Building project:[ InertialSenseCLTool - Debug ]----------"
	@$(MAKE) -f  "InertialSenseCLTool.mk"
clean:
	@echo "----------Cleaning project:[ InertialSenseCLTool - Debug ]----------"
	@$(MAKE) -f  "InertialSenseCLTool.mk" clean
